core\_db.exceptions.NotFoundException
=====================================

.. currentmodule:: core_db.exceptions

.. autoexception:: NotFoundException